theme: minima

title: My page On
author: adriellison
email: adriellisonki@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Edited this line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: adriellisonki # DO NOT include the @ character, or else the build will fail!
github_username: adriellison # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
